### ISSUE TITLE
Arc projectiles (Specifically the petrol bomb) seem to trigger early when arced upwards

### ISSUE THREAD

**Issue by ShadowBrian** [apetavern/sbox-grubs#264]
https://github.com/apetavern/sbox-grubs/assets/11138884/41d7bf28-a48d-450a-909a-a049a0ca6d6b

Not sure why or how it's doing this.

**Comment by dch-GH** [comment]
It's because when the arc gadget simulation runs out of segments it defaults to exploding the projectile, ignoring if the explosive component's `ExplodeAfter` is <= 0. I'll see about fixing it.
https://github.com/apetavern/sbox-grubs/blob/9458d42f8c8b8c0a14041981e7ec80815d350da9/code/Weapons/Gadget/Components/ArcPhysicsGadgetComponent.cs#L68

**Comment by matekdev** [comment]
fixed kinda
